common: &common
 adapter: mysql2

development:
  <<: *common
  database: todo_dbcharmer_development
  db_a:
    <<: *common
    database: todo_dbcharmer_development_a
  db_b:
    <<: *common
    database: todo_dbcharmer_development_b

test:
  <<: *common
  database: todo_dbcharmer_test
  db_a:
    <<: *common
    database: todo_dbcharmer_test_a
  db_b:
    <<: *common
    database: todo_dbcharmer_test_b
