default: &default
 adapter: mysql2

development:
  database: todo_dbcharmer_development
  <<: *default
  db_a:
    <<: *default
    database: todo_dbcharmer_development

test:
  database: todo_dbcharmer_test
  <<: *default
  db_a:
    <<: *default
    database: todo_dbcharmer_test

production:
  adapter: mysql2
  database: todo_dbcharmer_production
